#!/bin/bash                                                                                                                                                                                                                                                                       
#                                                                                                                                                                                                                                                                                 
#                                                                                                                                                                                                                                                                                 
#                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                  
set -eu                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                  
DOCKER_RUN_PATH=/var/run/docker/execdriver/native/                                                                                                                                                                                                                                
STATE_JSON=state.json                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                  
container=$1                                                                                                                                                                                                                                                                      
id="$(docker inspect -f '{{ .Id }}' $container)"                                                                                                                                                                                                                                  
state_file="$DOCKER_RUN_PATH/$container/$STATE_JSON"                                                                                                                                                                                                                              
veth="$(cat $state_file | jq -r '.config.networks[].host_interface_name' | grep veth)"                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                  
# Example just with 30% loss                                                                                                                                                                                                                                                      
tc qdisc replace dev $veth root netem loss 40%                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                  
# Example drop                                                                                                                                                                                                                                                                    
tc qdisc replace dev $veth root netem delay 75ms 100ms distribution normal                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                  
# Example restore                                                                                                                                                                                                                                                                 
tc qdisc del dev $veth root  